### ISSUE TITLE
Why the need to check for mAuth != null?

### ISSUE THREAD

**Issue by jeffrade** [depop/ClearableEditText#3]
https://github.com/depop/ClearableEditText/blob/master/app/src/main/java/com/example/barryirvine/clearableedittext/LoginActivity.java#L92

After failed login attempt, `mAuth` will still hold the `UserLoginTask` object and therefore user is unable to make anymore attempts to login since method will simply return.

I simply removed this check and return statement and was able to make multiple attemps after multiple login failures.

Is this a bug?  I can submit a PR if so.

**Comment by barrywe7** [comment]
This is actually copied code from one of the Google sample projects and the goal of this project is to showcase the ClearableEditText rather than the faux login process. I believe the purpose of the check is to stop you accidentally pressing the login button twice and creating two tasks. Also why is the failed login attempt still holding a reference to the task? It should be reset in both the onCancel and the onPostExecute so it should never have a task in that scenario.

**Comment by jeffrade** [comment]
@barrywe7 I see that now [here](https://github.com/depop/ClearableEditText/blob/master/app/src/main/java/com/example/barryirvine/clearableedittext/LoginActivity.java#L212).  That line is missing in my version of the file.  Thanks for the followup!
